name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        go: ['1.20']
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      # Run build of the application
      - name: Run build
        run: go build -v ./...

      # Run testing on the code
      - name: Run testing
        run: go test -v ./...
